// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd4Ggg3RpQxooupzso9C_b4e9tNAFU7Rw',
    appId: '1:744487376357:web:94d785522daf2d2f6b4b0c',
    messagingSenderId: '744487376357',
    projectId: 'farm2market-a9137',
    authDomain: 'farm2market-a9137.firebaseapp.com',
    storageBucket: 'farm2market-a9137.firebasestorage.app',
    measurementId: 'G-7N6TCV40RW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpvypfheFZ9JMqi5EFg6nj0rXvBO4liKU',
    appId: '1:744487376357:android:a2b2c3da0f459c456b4b0c',
    messagingSenderId: '744487376357',
    projectId: 'farm2market-a9137',
    storageBucket: 'farm2market-a9137.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBzcGFtqsMmr4Gx0tDg3pI0dUDvdM8DAZY',
    appId: '1:744487376357:ios:722ee619fabb542f6b4b0c',
    messagingSenderId: '744487376357',
    projectId: 'farm2market-a9137',
    storageBucket: 'farm2market-a9137.firebasestorage.app',
    iosClientId: '744487376357-73s8s31cihnd4gc3pdphfvj32635jebj.apps.googleusercontent.com',
    iosBundleId: 'com.example.farmapp',
  );

}